### ISSUE TITLE
Next Noetic Release

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros_control#449]
* [X] Python setuptools instead of distutils: https://github.com/ros-controls/ros_control/issues/429 (Melodic merge may be tricky but catkin available in Noetic should already support this)
* [ ] Technical debt from Noetic release Python3 port: https://github.com/ros-controls/ros_control/issues/448
* [x] Add function specifiers and modernize constructors https://github.com/ros-controls/ros_control/pull/453
* [X] Cherry pick #450 , rqt tool state fix
* [X] Cherry pick #454 , update docs

**Comment by bmagyar** [comment]
Cherry pick #450

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/24804
